"""
Django settings for JUDICO_HUB project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+*l0!f+wv-*re$!wx_bf0wv2&=3uskdk^b%kq_$785z8&$7qz0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Remove the default admin
    # 'django.contrib.admin',

    'admin_portal.apps.AdminPortalAdminConfig',  # Use the specific config class
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Add this line
    
    # Custom apps
    'authentication',  # Add this line
    'client_management',
    'task_management',
    'finance_management',
    'hr_management',
    'transaction_support',
    'document_repository',
    'communication',
    'governance',
    'compliance',
    'kyc_app',
    'lawyer_portal',
    'client_portal',
    'theme',
    'import_export',
    'quotes',  # Add the quotes app
    'contract_management',  # Add the contract management app
    'sequences',
    # Third-party apps
    'rest_framework',
    'crispy_forms',
    'channels',
    'tailwind',
    'django_extensions',  # Add django_extensions for runscript command
    'widget_tweaks',  # Add django-widget-tweaks
    'django_htmx'  # Add django-htmx
]

# Update these settings
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware'

]

ROOT_URLCONF = 'JUDICO_HUB.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
        BASE_DIR / 'templates',  # Project-level templates
        BASE_DIR / 'JUDICO_HUB' / 'templates',
        BASE_DIR / 'admin_portal' / 'templates',
    ],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'quotes.context_processors.daily_quote',  # Add the quotes context processor
        ],
    },
}]

WSGI_APPLICATION = 'JUDICO_HUB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'judico_db',
        'USER': 'postgres',
        'PASSWORD': 'Launaxe123!',  # Updated from 'your_password'
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

TAILWIND_APP_NAME =  'theme'
NPM_BIN_PATH='C:/Program Files/nodejs/npm.cmd'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT= BASE_DIR /'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Add project root static directory
    BASE_DIR / 'JUDICO_HUB' / 'static',
    BASE_DIR / 'theme'/ 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PAGINATE_BY= 10  # Default pagination setting