# Generated by Django 5.1.7 on 2025-07-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
    ]
