# Generated by Django 5.1.7 on 2025-07-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_create_initial_departments'),
        ('hr_management', 'XXXX_create_initial_departments'),
    ]

    operations = [
    ]
