# Generated by Django 5.2.3 on 2025-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0003_merge_20250707_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('scheduled', 'Scheduled'), ('overdue', 'Overdue')], default='scheduled', max_length=20),
        ),
    ]
