# Generated by Django 5.1.7 on 2025-08-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0005_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity_type', models.CharField(choices=[('legal_research', 'Legal Research'), ('client_consultation', 'Client Consultation'), ('court_appearance', 'Court Appearance'), ('document_preparation', 'Document Preparation'), ('case_management', 'Case Management'), ('meeting', 'Meeting'), ('administrative', 'Administrative'), ('training', 'Training'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('client_case', models.CharField(blank=True, help_text='Client name or case reference', max_length=200)),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Hours worked (e.g., 7.5)', max_digits=5)),
                ('is_billable', models.BooleanField(default=True)),
                ('billable_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('billable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('billed', 'Billed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='hr_management.employee')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
