# Generated by Django 5.1.7 on 2025-09-08 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('legal_research', 'Legal Research'), ('client_consultation', 'Client Consultation'), ('court_appearance', 'Court Appearance'), ('document_preparation', 'Document Preparation'), ('case_management', 'Case Management'), ('meeting', 'Meeting'), ('administrative', 'Administrative'), ('training', 'Training'), ('other', 'Other')], default='administrative', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('client_case', models.CharField(blank=True, help_text='Client name or case reference', max_length=200)),
                ('is_manual', models.BooleanField(default=False, help_text='True if manually started, False if automatic from login')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='hr_management.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Time Session',
                'verbose_name_plural': 'User Time Sessions',
                'ordering': ['-login_time'],
            },
        ),
    ]
