# Generated by Django X.X.X on YYYY-MM-DD HH:MM

from django.db import migrations

def create_departments(apps, schema_editor):
    Department = apps.get_model('hr_management', 'Department')
    departments = [
        {"name": "Legal", "description": "Legal department"},
        {"name": "Finance", "description": "Finance department"},
        {"name": "HR", "description": "Human Resources department"},
        {"name": "IT", "description": "Information Technology department"},
        {"name": "Administration", "description": "Administration department"},
    ]
    for dept in departments:
        Department.objects.create(**dept)

class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_departments),
    ]