# Generated by Django 5.2.3 on 2025-07-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('vessel', 'Vessel'), ('aircraft', 'Aircraft')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('list_type', models.CharField(choices=[('sanctions', 'Sanctions List'), ('pep', 'Politically Exposed Persons'), ('terrorism', 'Terrorism Watch List'), ('crime', 'Criminal Watch List'), ('custom', 'Custom List')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(choices=[('customer_onboarding', 'Customer Onboarding'), ('transaction_monitoring', 'Transaction Monitoring'), ('periodic_review', 'Periodic Review'), ('ad_hoc', 'Ad-hoc Screening')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('flagged', 'Flagged'), ('cleared', 'Cleared')], default='pending', max_length=20)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_screenings', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='aml_system.entity')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_screenings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('wire_transfer', 'Wire Transfer'), ('cash_deposit', 'Cash Deposit'), ('cash_withdrawal', 'Cash Withdrawal'), ('check_deposit', 'Check Deposit'), ('ach_transfer', 'ACH Transfer'), ('international_transfer', 'International Transfer')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='aml_system.entity')),
                ('sender_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='aml_system.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('screening_match', 'Screening Match'), ('suspicious_transaction', 'Suspicious Transaction'), ('threshold_breach', 'Threshold Breach'), ('pattern_detection', 'Pattern Detection'), ('manual_review', 'Manual Review Required')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='new', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='aml_system.entity')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='aml_system.screening')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='aml_system.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WatchListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_numbers', models.TextField(blank=True, null=True)),
                ('addresses', models.TextField(blank=True, null=True)),
                ('reason_for_listing', models.TextField(blank=True, null=True)),
                ('date_listed', models.DateField(blank=True, null=True)),
                ('watch_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='aml_system.watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match'), ('phonetic', 'Phonetic Match'), ('fuzzy', 'Fuzzy Match')], max_length=20)),
                ('match_score', models.FloatField()),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aml_system.screening')),
                ('watch_list_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aml_system.watchlistentry')),
            ],
        ),
    ]
