# Generated by Django 5.1.7 on 2025-08-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0005_alter_client_code_case_casedocument_caseupdate'),
        ('finance_management', '0005_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='created_by',
            new_name='submitted_by',
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance_management.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_level',
            field=models.CharField(choices=[('STAFF', 'Staff Level'), ('SUPERVISOR', 'Supervisor Level'), ('MANAGER', 'Manager Level'), ('PARTNER', 'Partner Level'), ('EXECUTIVE', 'Executive Level')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='audit_trail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expense',
            name='billable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='billable_status',
            field=models.CharField(choices=[('BILLABLE', 'Billable to Client'), ('NON_BILLABLE', 'Non-Billable'), ('PARTIALLY_BILLABLE', 'Partially Billable')], default='NON_BILLABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='case_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='client_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='client_management.case'),
        ),
        migrations.AddField(
            model_name='expense',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='compliance_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_compliant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance_management.journalentry'),
        ),
        migrations.AddField(
            model_name='expense',
            name='matter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('RECONCILED', 'Reconciled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='supporting_documents',
            field=models.FileField(blank=True, upload_to='expenses/supporting_docs/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OFFICE_SUPPLIES', 'Office Supplies'), ('OFFICE_EQUIPMENT', 'Office Equipment'), ('OFFICE_RENT', 'Office Rent'), ('OFFICE_MAINTENANCE', 'Office Maintenance'), ('OFFICE_INSURANCE', 'Office Insurance'), ('OFFICE_SECURITY', 'Office Security'), ('UTILITIES_ELECTRICITY', 'Electricity'), ('UTILITIES_WATER', 'Water'), ('UTILITIES_GAS', 'Gas'), ('UTILITIES_INTERNET', 'Internet & Communications'), ('UTILITIES_PHONE', 'Phone Services'), ('UTILITIES_CABLE', 'Cable & TV'), ('LEGAL_FEES', 'Legal Fees'), ('ACCOUNTING_FEES', 'Accounting Fees'), ('CONSULTING_FEES', 'Consulting Fees'), ('PROFESSIONAL_DEVELOPMENT', 'Professional Development'), ('BAR_ASSOCIATION_FEES', 'Bar Association Fees'), ('CONTINUING_EDUCATION', 'Continuing Legal Education'), ('COURT_FILING_FEES', 'Court Filing Fees'), ('PROCESS_SERVING', 'Process Serving'), ('EXPERT_WITNESS_FEES', 'Expert Witness Fees'), ('INVESTIGATION_COSTS', 'Investigation Costs'), ('TRAVEL_EXPENSES', 'Travel Expenses'), ('MEAL_EXPENSES', 'Meal Expenses'), ('ACCOMMODATION', 'Accommodation'), ('TRANSPORTATION', 'Transportation'), ('MARKETING_ADVERTISING', 'Marketing & Advertising'), ('BUSINESS_DEVELOPMENT', 'Business Development'), ('NETWORKING_EVENTS', 'Networking Events'), ('PUBLICATIONS', 'Publications & Subscriptions'), ('SOFTWARE_LICENSES', 'Software Licenses'), ('TECHNOLOGY_MAINTENANCE', 'Technology Maintenance'), ('DATA_BACKUP', 'Data Backup & Security'), ('CLOUD_SERVICES', 'Cloud Services'), ('STAFF_SALARIES', 'Staff Salaries'), ('STAFF_BENEFITS', 'Staff Benefits'), ('STAFF_TRAINING', 'Staff Training'), ('STAFF_EQUIPMENT', 'Staff Equipment'), ('COMPLIANCE_FEES', 'Compliance Fees'), ('REGULATORY_FILINGS', 'Regulatory Filings'), ('AUDIT_FEES', 'Audit Fees'), ('LICENSING_FEES', 'Licensing Fees'), ('OTHER', 'Other Expenses')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='finance_man_expense_41eaad_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='finance_man_status_424fac_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='finance_man_categor_a13831_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['client_case'], name='finance_man_client__5ecac0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['billable_status'], name='finance_man_billabl_fd6f0a_idx'),
        ),
    ]
