# Generated by Django 5.1.7 on 2025-08-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0006_alter_expense_options_and_more'),
    ]

    operations = [
        # Add new fields to Account model
        migrations.AddField(
            model_name='account',
            name='account_category',
            field=models.CharField(
                choices=[
                    ('CURRENT_ASSET', 'Current Asset'),
                    ('FIXED_ASSET', 'Fixed Asset'),
                    ('INTANGIBLE_ASSET', 'Intangible Asset'),
                    ('INVESTMENT', 'Investment'),
                    ('CURRENT_LIABILITY', 'Current Liability'),
                    ('LONG_TERM_LIABILITY', 'Long Term Liability'),
                    ('OWNERS_EQUITY', 'Owner\'s Equity'),
                    ('RETAINED_EARNINGS', 'Retained Earnings'),
                    ('OPERATING_REVENUE', 'Operating Revenue'),
                    ('NON_OPERATING_REVENUE', 'Non-Operating Revenue'),
                    ('OPERATING_EXPENSE', 'Operating Expense'),
                    ('NON_OPERATING_EXPENSE', 'Non-Operating Expense'),
                ],
                default='CURRENT_ASSET',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(
                choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')],
                default='DEBIT',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='is_bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_cash_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_contra_account',
            field=models.BooleanField(default=False),
        ),
        
        # Create Journal model
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('journal_type', models.CharField(
                    choices=[
                        ('GENERAL', 'General Journal'),
                        ('SALES', 'Sales Journal'),
                        ('PURCHASE', 'Purchase Journal'),
                        ('CASH_RECEIPTS', 'Cash Receipts Journal'),
                        ('CASH_DISBURSEMENTS', 'Cash Disbursements Journal'),
                        ('ADJUSTING', 'Adjusting Journal'),
                        ('CLOSING', 'Closing Journal'),
                    ],
                    max_length=20
                )),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')],
                    default='ACTIVE',
                    max_length=20
                )),
                ('next_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journals',
                'ordering': ['code'],
            },
        ),
        
        # Create AccountingPeriod model
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(
                    choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')],
                    default='OPEN',
                    max_length=20
                )),
                ('is_current', models.BooleanField(default=False)),
                ('is_adjustment_period', models.BooleanField(default=False)),
                ('opening_equity', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('closing_equity', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('closing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting Periods',
                'ordering': ['-start_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        
        # Create AccountBalance model
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('period_debits', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('period_credits', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.00, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finance_management.account')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='finance_management.accountingperiod')),
            ],
            options={
                'verbose_name_plural': 'Account Balances',
                'ordering': ['account__code', 'period__start_date'],
                'unique_together': {('account', 'period')},
            },
        ),
        
        # Create FinancialStatement model
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(
                    choices=[
                        ('TRIAL_BALANCE', 'Trial Balance'),
                        ('BALANCE_SHEET', 'Balance Sheet'),
                        ('INCOME_STATEMENT', 'Income Statement'),
                        ('CASH_FLOW', 'Statement of Cash Flows'),
                    ],
                    max_length=20
                )),
                ('as_of_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('format', models.CharField(
                    choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML')],
                    default='HTML',
                    max_length=10
                )),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_statements', to='auth.user')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='finance_management.accountingperiod')),
            ],
            options={
                'verbose_name_plural': 'Financial Statements',
                'ordering': ['-generated_at'],
                'unique_together': {('statement_type', 'period', 'as_of_date')},
            },
        ),
        
        # Update JournalEntry model - make fields nullable initially
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance_management.journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='finance_management.accountingperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to='auth.user'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_entries', to='auth.user'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        
        # Update JournalEntryLine model
        migrations.AddField(
            model_name='journalentryline',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_closing',
            field=models.BooleanField(default=False),
        ),
    ]
