# Generated by Django 5.1.7 on 2025-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0007_add_accounting_fields'),
    ]

    operations = [
        # Remove the old balance field
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
