# Generated by Django 5.1.7 on 2025-09-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0010_add_accounts_payable'),
    ]

    operations = [
        # Increase report_type field length
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(max_length=25, choices=[
                ('cash_flow', 'Cash Flow Report'),
                ('profit_loss', 'Profit & Loss Statement'),
                ('balance_sheet', 'Balance Sheet'),
                ('accounts_receivable', 'Accounts Receivable Aging'),
                ('accounts_payable', 'Accounts Payable Aging'),
                ('expense_analysis', 'Expense Analysis Report'),
                ('revenue_analysis', 'Revenue Analysis Report'),
                ('working_capital', 'Working Capital Report'),
                ('collection_performance', 'Collection Performance Report'),
                ('vendor_analysis', 'Vendor Analysis Report'),
                ('client_revenue', 'Client Revenue Report'),
                ('monthly_summary', 'Monthly Financial Summary'),
            ]),
        ),
        # Handle expense_category field - make it nullable first
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='finance_management.expensecategory'
            ),
        ),
    ]
