# Generated by Django 5.2.3 on 2025-07-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('lawyer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='lawyer_portal.lawyerprofile'),
        ),
    ]
