# Generated by Django 5.2.3 on 2025-07-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_client_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='case_type',
            field=models.CharField(choices=[('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('corporate', 'Corporate Law'), ('family', 'Family Law'), ('employment', 'Employment Law'), ('real_estate', 'Real Estate Law'), ('intellectual_property', 'Intellectual Property'), ('tax', 'Tax Law'), ('immigration', 'Immigration Law'), ('personal_injury', 'Personal Injury'), ('contract', 'Contract Law'), ('bankruptcy', 'Bankruptcy Law'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
