# Generated by Django 5.1.7 on 2025-07-31 14:43

import client_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0003_client_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(default=client_management.models.generate_client_code, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
