# Generated by Django 5.1.7 on 2025-07-31 15:22

import client_management.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_client_code_alter_client_name'),
        ('lawyer_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(default=client_management.models.generate_client_code, editable=False, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=client_management.models.generate_case_code, editable=False, max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('case_type', models.CharField(choices=[('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('corporate', 'Corporate Law'), ('family', 'Family Law'), ('employment', 'Employment Law'), ('real_estate', 'Real Estate Law'), ('intellectual_property', 'Intellectual Property'), ('tax', 'Tax Law'), ('immigration', 'Immigration Law'), ('personal_injury', 'Personal Injury'), ('contract', 'Contract Law'), ('bankruptcy', 'Bankruptcy Law'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('court_date', models.DateTimeField(blank=True, null=True)),
                ('court_location', models.CharField(blank=True, max_length=200)),
                ('case_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='client_management.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='lawyer_portal.lawyerprofile')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='case_documents/')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('evidence', 'Evidence'), ('correspondence', 'Correspondence'), ('court_filing', 'Court Filing'), ('research', 'Legal Research'), ('other', 'Other')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='client_management.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('progress', 'Progress Update'), ('meeting', 'Meeting/Consultation'), ('document', 'Document Filed'), ('court', 'Court Appearance'), ('research', 'Legal Research'), ('communication', 'Client Communication'), ('milestone', 'Milestone Achieved'), ('issue', 'Issue/Problem'), ('resolution', 'Resolution'), ('other', 'Other')], default='progress', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('hours_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_billable', models.BooleanField(default=True)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='client_management.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
