# Generated by Django 5.1.7 on 2025-07-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
    ]
