# Generated by Django 5.2.3 on 2025-07-10 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_auto_20250710_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('board', 'Board Meeting'), ('committee', 'Committee Meeting'), ('general', 'General Meeting'), ('emergency', 'Emergency Meeting'), ('quarterly', 'Quarterly Review'), ('annual', 'Annual Meeting')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Meeting duration (e.g., 1:30:00 for 1 hour 30 minutes)')),
                ('location', models.CharField(blank=True, help_text='Physical location or meeting room', max_length=200)),
                ('virtual_link', models.URLField(blank=True, help_text='Video conference link')),
                ('agenda', models.TextField(blank=True)),
                ('minutes', models.TextField(blank=True, help_text='Meeting minutes/notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date'],
            },
        ),
    ]
