# Generated by Django 5.2.3 on 2025-07-10 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('policy_compliance', 'Policy Compliance Report'), ('meeting_summary', 'Meeting Summary Report'), ('governance_metrics', 'Governance Metrics Report'), ('quarterly_review', 'Quarterly Review Report'), ('annual_summary', 'Annual Summary Report'), ('custom', 'Custom Report')], max_length=30)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='generating', max_length=20)),
                ('period_start', models.DateField(help_text='Report period start date')),
                ('period_end', models.DateField(help_text='Report period end date')),
                ('data', models.JSONField(default=dict, help_text='Report data and metrics')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
