# Generated by Django 5.1.3 on 2025-04-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='KYCWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft - Initial Information Entered'), ('SUBMITTED', 'Submitted - Pending Initial Review'), ('DOC_REVIEW', 'Document Review - Validating Documents'), ('SCREENING', 'Screening - Running Checks'), ('INVESTIGATION', 'Investigation - Enhanced Due Diligence'), ('APPROVAL_PENDING', 'Approval Pending - Awaiting Final Decision'), ('APPROVED', 'Approved - KYC Complete'), ('REJECTED', 'Rejected - KYC Failed'), ('EXPIRED', 'Expired - Renewal Required')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('days_in_current_state', models.IntegerField(default=0)),
                ('screening_date', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('history', models.JSONField(default=list, help_text='List of previous states with timestamps')),
                ('kyc_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='kyc_app.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Workflow State',
                'verbose_name_plural': 'KYC Workflow States',
            },
        ),
    ]
