# Generated by Django 5.1.3 on 2025-04-24 14:16

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q          # ← NEW

class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app',
         '0002_kycprofile_completion_percentage_kycprofile_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycbusiness',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kycworkflowstate',
            name='business_kyc',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workflow_state',
                to='kyc_app.kycbusiness',
            ),
        ),
        migrations.AlterField(
            model_name='kycworkflowstate',
            name='kyc_profile',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workflow_state',
                to='kyc_app.kycprofile',
            ),
        ),
        migrations.AddConstraint(
            model_name='kycworkflowstate',
            constraint=models.CheckConstraint(
                check=Q(kyc_profile__isnull=False) | Q(business_kyc__isnull=False),
                name='either_profile_or_business_required',
            ),
        ),
    ]
