# Generated by Django 5.1.3 on 2025-04-24 21:20

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q  # NEW import

class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app',
         '0003_kycbusiness_is_draft_kycworkflowstate_business_kyc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(
                    choices=[
                        ('INDIVIDUAL', 'Individual KYC Report'),
                        ('BUSINESS', 'Business KYC Report')
                    ],
                    max_length=20)),
                ('summary', models.TextField(
                    help_text='Executive summary of the KYC report')),
                ('risk_assessment', models.TextField(
                    help_text='Details of risk assessment')),
                ('decision', models.CharField(
                    choices=[
                        ('APPROVED', 'Approved'),
                        ('REJECTED', 'Rejected')
                    ],
                    max_length=20)),
                ('decision_reason', models.TextField(
                    help_text='Reason for approval or rejection')),
                ('generated_by', models.CharField(
                    help_text='User who generated the report',
                    max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_report', models.FileField(blank=True, null=True,
                                                upload_to='kyc_reports/')),
                ('screening_result', models.JSONField(
                    default=dict,
                    help_text='Raw screening results from third-party services')),
                ('sanctions_check', models.BooleanField(default=False)),
                ('pep_check', models.BooleanField(default=False)),
                ('adverse_media_check', models.BooleanField(default=False)),
                ('edd_performed', models.BooleanField(
                    default=False,
                    help_text='Whether Enhanced Due Diligence was performed')),
                ('edd_details', models.TextField(blank=True, null=True)),
                ('business_kyc', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='kyc_reports',
                    to='kyc_app.kycbusiness')),
                ('kyc_profile', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='kyc_reports',
                    to='kyc_app.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Report',
                'verbose_name_plural': 'KYC Reports',
                'ordering': ['-generated_at'],
                'constraints': [
                    models.CheckConstraint(
                        check=Q(kyc_profile__isnull=False) |
                              Q(business_kyc__isnull=False),
                        name='either_individual_or_business_report_required',
                    )
                ],
            },
        ),
    ]
