# Generated by Django 5.1.3 on 2025-04-25 08:31

import kyc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to=kyc_app.models.customer_document_path),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to=kyc_app.models.business_document_path),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to=kyc_app.models.business_document_path),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='id_document_file',
            field=models.FileField(blank=True, null=True, upload_to=kyc_app.models.profile_document_path),
        ),
    ]
