# Generated by Django 5.1.3 on 2025-04-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0006_alter_document_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc_app.kycbusiness'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('RESIDENCE_PERMIT', 'Residence Permit'), ('UTILITY_BILL', 'Utility Bill'), ('BANK_STATEMENT', 'Bank Statement'), ('REGISTRATION_CERT', 'Business Registration Certificate'), ('TAX_CERT', 'Tax Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc_app.kycprofile'),
        ),
    ]
