# Generated by Django 5.1.3 on 2025-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0007_document_business_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycbusiness',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Business Checking'), ('savings', 'Business Savings'), ('investment', 'Investment Account'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='annual_revenue',
            field=models.CharField(choices=[('less_than_100k', 'Less than $100,000'), ('100k_500k', '$100,000 - $500,000'), ('500k_1m', '$500,000 - $1,000,000'), ('1m_5m', '$1,000,000 - $5,000,000'), ('5m_10m', '$5,000,000 - $10,000,000'), ('more_than_10m', 'More than $10,000,000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='business_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='business_type',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation'), ('nonprofit', 'Non-Profit Organization'), ('trust', 'Trust'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='industry_sector',
            field=models.CharField(choices=[('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance & Insurance'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('hospitality', 'Hospitality'), ('education', 'Education'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='ownership_structure',
            field=models.CharField(choices=[('single_owner', 'Single Owner'), ('multiple_partners', 'Multiple Partners'), ('public_company', 'Public Company'), ('private_company', 'Private Company'), ('government_owned', 'Government Owned'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='source_of_funds',
            field=models.CharField(choices=[('business_revenue', 'Business Revenue'), ('investments', 'Investments'), ('loans', 'Loans/Credit'), ('personal_capital', 'Personal Capital'), ('grants', 'Grants/Subsidies'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='swift_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kycbusiness',
            name='transaction_volume',
            field=models.CharField(choices=[('less_than_10k', 'Less than $10,000'), ('10k_50k', '$10,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('100k_500k', '$100,000 - $500,000'), ('more_than_500k', 'More than $500,000')], max_length=100),
        ),
    ]
