# Generated by Django 5.1.7 on 2025-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0008_alter_kycbusiness_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapessoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Private API key for accessing the Capesso API', max_length=255)),
                ('base_url', models.URLField(default='https://api.capesso.com', help_text='Base URL for the Capesso API')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capesso Configuration',
                'verbose_name_plural': 'Capesso Configurations',
            },
        ),
    ]
