# Generated by Django 5.2.3 on 2025-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The quote text')),
                ('author', models.CharField(blank=True, help_text='Author of the quote', max_length=255, null=True)),
                ('display_date', models.DateField(blank=True, help_text='Specific date to display this quote (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quote is active and can be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['display_date', 'created_at'],
            },
        ),
    ]
